on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt install lua5.1
          sudo apt-get install lua-sec
          sudo apt-get install lua-socket
          mkdir work_dir
      - uses: actions/checkout@v4
        with:
          path: work_dir
      - uses: actions/checkout@v4
        with:
          repository: 'https://github.com/Gethe/wow-ui-source.git'
          path: work_dir
      - run: |
          cd work_dir
          ls